import { HYDRAULIC_VALVE_CATEGORY } from '@/types/category';
import type { CanonicalMappingEntry } from '@/types/canonicalAttribute';

function connectorEntry(
  options: Omit<CanonicalMappingEntry, 'category' | 'attributeKey' | 'evidence'> & {
    attributeKey?: string;
  },
): CanonicalMappingEntry {
  return {
    category: HYDRAULIC_VALVE_CATEGORY,
    attributeKey: options.attributeKey ?? 'connector_type',
    evidence: 'code',
    ...options,
  };
}

const VICKERS_DG4V_DIN_BASE = {
  canonicalKey: 'DIN_VALVE_CONNECTOR',
  canonicalValue: 'DIN_VALVE_CONNECTOR',
  displayValue: 'DIN valf soketi / ISO 4400',
  connectorFamilyKey: 'DIN_VALVE_CONNECTOR' as const,
  connectorStandardKey: 'ISO4400_DIN43650',
  confidence: 'high' as const,
  requiresCatalogCheck: false,
};

/** Connector_type canonical mappings (physical family + non-critical options). */
export const CONNECTOR_CANONICAL_MAPPING_ENTRIES: CanonicalMappingEntry[] = [
  connectorEntry({
    id: 'rexroth_we6_connector_k4',
    manufacturer: 'Rexroth',
    series: '4WE6',
    rawToken: 'K4',
    canonicalKey: 'DIN_VALVE_CONNECTOR',
    canonicalValue: 'DIN_VALVE_CONNECTOR',
    displayValue: 'DIN valf soketi / EN 175301-803',
    connectorFamilyKey: 'DIN_VALVE_CONNECTOR',
    connectorStandardKey: 'DIN_43650_FORM_A_EN_175301_803',
    confidence: 'high',
    requiresCatalogCheck: false,
    notes: ['DIN 43650 / ISO 4400 / EN 175301-803 ailesi'],
  }),
  connectorEntry({
    id: 'rexroth_we6_connector_c4z',
    manufacturer: 'Rexroth',
    series: '4WE6',
    rawToken: 'C4Z',
    canonicalKey: 'AMP_JUNIOR_TIMER',
    canonicalValue: 'AMP_JUNIOR_TIMER',
    displayValue: 'AMP / Junior Timer konnektör',
    connectorFamilyKey: 'AMP_JUNIOR_TIMER',
    confidence: 'high',
    requiresCatalogCheck: false,
  }),
  connectorEntry({
    id: 'yuken_dsg_connector_n',
    manufacturer: 'Yuken',
    series: 'DSG-01',
    rawToken: 'N',
    canonicalKey: 'PLUG_IN_CONNECTOR',
    canonicalValue: 'PLUG_IN_CONNECTOR',
    displayValue: 'Fişli konnektör',
    connectorFamilyKey: 'PLUG_IN_CONNECTOR',
    isGenericConnector: true,
    confidence: 'medium',
    requiresCatalogCheck: true,
  }),
  connectorEntry({
    id: 'yuken_dsg_connector_n1',
    manufacturer: 'Yuken',
    series: 'DSG-01',
    rawToken: 'N1',
    canonicalKey: 'PLUG_IN_CONNECTOR',
    canonicalValue: 'PLUG_IN_CONNECTOR',
    displayValue: 'Fişli konnektör',
    connectorFamilyKey: 'PLUG_IN_CONNECTOR',
    hasIndicatorLight: true,
    connectorOptions: ['INDICATOR_LIGHT'],
    displayDetail: 'Işıklı',
    isGenericConnector: true,
    confidence: 'medium',
    requiresCatalogCheck: true,
  }),

  // Atos DHI/DHU: X = connector not included / order separately
  connectorEntry({
    id: 'atos_dhi_connector_x_no_connector',
    manufacturer: 'Atos',
    series: 'DHI',
    rawToken: 'X',
    canonicalKey: 'NO_CONNECTOR_INCLUDED',
    canonicalValue: 'NO_CONNECTOR_INCLUDED',
    displayValue: 'Konnektör dahil değil / ayrı sipariş edilir',
    connectorFamilyKey: 'NO_CONNECTOR',
    confidence: 'medium',
    requiresCatalogCheck: false,
    notes: ['Atos kod seçeneği: konnektör dahil değil.'],
  }),
  connectorEntry({
    id: 'atos_dhu_connector_x_no_connector',
    manufacturer: 'Atos',
    series: 'DHU',
    rawToken: 'X',
    canonicalKey: 'NO_CONNECTOR_INCLUDED',
    canonicalValue: 'NO_CONNECTOR_INCLUDED',
    displayValue: 'Konnektör dahil değil / ayrı sipariş edilir',
    connectorFamilyKey: 'NO_CONNECTOR',
    confidence: 'medium',
    requiresCatalogCheck: false,
    notes: ['Atos kod seçeneği: konnektör dahil değil.'],
  }),

  // Vickers DG4V family (DG4V-3, DG4V-5, …) — seriesFamily avoids per-size duplication
  connectorEntry({
    id: 'vickers_dg4v_family_connector_u',
    manufacturer: 'Vickers',
    seriesFamily: 'DG4V',
    rawToken: 'U',
    ...VICKERS_DG4V_DIN_BASE,
  }),
  connectorEntry({
    id: 'vickers_dg4v_family_connector_u1',
    manufacturer: 'Vickers',
    seriesFamily: 'DG4V',
    rawToken: 'U1',
    ...VICKERS_DG4V_DIN_BASE,
    hasPgPlug: true,
    connectorOptions: ['PG11_ENTRY'],
    displayDetail: 'PG11 girişli',
  }),
  connectorEntry({
    id: 'vickers_dg4v_family_connector_u6',
    manufacturer: 'Vickers',
    seriesFamily: 'DG4V',
    rawToken: 'U6',
    ...VICKERS_DG4V_DIN_BASE,
    hasIndicatorLight: true,
    connectorOptions: ['INDICATOR_LIGHT'],
    displayDetail: 'Işıklı',
  }),
  connectorEntry({
    id: 'vickers_dg4v_family_connector_kup4',
    manufacturer: 'Vickers',
    seriesFamily: 'DG4V',
    rawToken: 'KUP4',
    canonicalKey: 'AMP_JUNIOR_TIMER',
    canonicalValue: 'AMP_JUNIOR_TIMER',
    displayValue: 'AMP / Junior Timer konnektör',
    connectorFamilyKey: 'AMP_JUNIOR_TIMER',
    confidence: 'high',
    requiresCatalogCheck: false,
  }),
  connectorEntry({
    id: 'vickers_dg4v_family_connector_kup5',
    manufacturer: 'Vickers',
    seriesFamily: 'DG4V',
    rawToken: 'KUP5',
    canonicalKey: 'DEUTSCH_CONNECTOR',
    canonicalValue: 'DEUTSCH_CONNECTOR',
    displayValue: 'Deutsch konnektör',
    connectorFamilyKey: 'DEUTSCH_CONNECTOR',
    confidence: 'high',
    requiresCatalogCheck: false,
  }),
  connectorEntry({
    id: 'vickers_dg4v_family_connector_kupm4l',
    manufacturer: 'Vickers',
    seriesFamily: 'DG4V',
    rawToken: 'KUPM4L',
    canonicalKey: 'M12_4_PIN',
    canonicalValue: 'M12_4_PIN',
    displayValue: 'M12 4-pin konnektör',
    connectorFamilyKey: 'M12_CONNECTOR',
    pinCount: 4,
    confidence: 'high',
    requiresCatalogCheck: false,
  }),

  // Category-wide fallbacks for catalog examples without manufacturer-specific rows
  connectorEntry({
    id: 'connector_k4_generic',
    rawToken: 'K4',
    canonicalKey: 'DIN_VALVE_CONNECTOR',
    canonicalValue: 'DIN_VALVE_CONNECTOR',
    displayValue: 'DIN valf soketi / EN 175301-803',
    connectorFamilyKey: 'DIN_VALVE_CONNECTOR',
    connectorStandardKey: 'DIN_43650_FORM_A_EN_175301_803',
    confidence: 'high',
    requiresCatalogCheck: false,
  }),
  connectorEntry({
    id: 'connector_c4z_generic',
    rawToken: 'C4Z',
    canonicalKey: 'AMP_JUNIOR_TIMER',
    canonicalValue: 'AMP_JUNIOR_TIMER',
    displayValue: 'AMP / Junior Timer konnektör',
    connectorFamilyKey: 'AMP_JUNIOR_TIMER',
    confidence: 'high',
    requiresCatalogCheck: false,
  }),
  connectorEntry({
    id: 'connector_n_generic',
    rawToken: 'N',
    canonicalKey: 'PLUG_IN_CONNECTOR',
    canonicalValue: 'PLUG_IN_CONNECTOR',
    displayValue: 'Fişli konnektör',
    connectorFamilyKey: 'PLUG_IN_CONNECTOR',
    isGenericConnector: true,
    confidence: 'medium',
    requiresCatalogCheck: true,
  }),
  connectorEntry({
    id: 'connector_n1_generic',
    rawToken: 'N1',
    canonicalKey: 'PLUG_IN_CONNECTOR',
    canonicalValue: 'PLUG_IN_CONNECTOR',
    displayValue: 'Fişli konnektör',
    connectorFamilyKey: 'PLUG_IN_CONNECTOR',
    hasIndicatorLight: true,
    connectorOptions: ['INDICATOR_LIGHT'],
    displayDetail: 'Işıklı',
    isGenericConnector: true,
    confidence: 'medium',
    requiresCatalogCheck: true,
  }),
];
